name: vitapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-128.0.dev <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  avatar_glow: ^3.0.1
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
