// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLD2dqaaRygeLWaFx05bONRNcSmwGMFG4',
    appId: '1:357247682443:web:95a059aff321c838c8d18e',
    messagingSenderId: '357247682443',
    projectId: 'vtapp-85fa1',
    authDomain: 'vtapp-85fa1.firebaseapp.com',
    storageBucket: 'vtapp-85fa1.appspot.com',
    measurementId: 'G-MBQ8SR2748',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3h1d3PR06tnMoDsCZJg6VZFZxgyTn_c',
    appId: '1:357247682443:android:31cf844f224c4139c8d18e',
    messagingSenderId: '357247682443',
    projectId: 'vtapp-85fa1',
    storageBucket: 'vtapp-85fa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_F32UGKpZi6VaiUL3nGsO29f35auP4o',
    appId: '1:357247682443:ios:e8f6d775c62be270c8d18e',
    messagingSenderId: '357247682443',
    projectId: 'vtapp-85fa1',
    storageBucket: 'vtapp-85fa1.appspot.com',
    iosBundleId: 'com.example.vitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_F32UGKpZi6VaiUL3nGsO29f35auP4o',
    appId: '1:357247682443:ios:2496bcf80d177cc6c8d18e',
    messagingSenderId: '357247682443',
    projectId: 'vtapp-85fa1',
    storageBucket: 'vtapp-85fa1.appspot.com',
    iosBundleId: 'com.example.vitapp.RunnerTests',
  );
}
